query getUserByEmail($paginationInput: FindPaginatedTodosInput!, $user: GetUserByEmailInput!){
    getUserByEmail(user: $user){
        email
        firstName
        id
        lastName
        registrationDate
        registrationNumber
        todos(paginationInput: $paginationInput){
            action
            category
            id
            isDone
        }
        userName
    }
}